[project]
name = "ublue-images"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<4.0"
authors = [{ name = "Joona Purkamo", email = "joona@purkamo.me" }]
dependencies = [
  "joblib>=1.5.3",
  "loguru>=0.7.3",
  "pydantic>=2.13.3",
  "python-dotenv>=1.2.1",
  "requests>=2.34.1",
]

[dependency-groups]
dev = [
  "datamodel-code-generator>=0.56.1",
]

[build-system]
requires = ["uv_build<1.0.0"]
build-backend = "uv_build"

[tool.ruff]
indent-width = 4
line-length = 100

[tool.ruff.lint]
fixable = ["ALL"]
