[project]
name = "ublue-images"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14,<4.0"
authors = [{ name = "Joona Purkamo", email = "joona@purkamo.me" }]
dependencies = [
  "loguru>=0.7.3",
  "pydantic>=2.13.3",
  "python-dotenv>=1.2.1",
  "pyyaml>=6.0.3",
  "requests>=2.32.5",
  "typer>=0.26.7",
]

[project.scripts]
ublue-images = "ublue_images.cli:app"

[dependency-groups]
dev = [
  "datamodel-code-generator>=0.56.1",
  "ruff>=0.16.1",
  "ty>=0.0.65",
]

[build-system]
requires = ["uv_build<1.0.0"]
build-backend = "uv_build"

[tool.ruff]
indent-width = 4
line-length = 120

[tool.uv]
exclude-newer = "3 days"
