name: bluebuild
on:
  schedule:
    - cron: "30 6 * * *" # 06:30 UTC
  workflow_dispatch: # allow manually triggering builds
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubicloud-standard-4
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          - kinoite-nvidia.yml
          - kinoite.yml
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download ChatWise RPM
        run: |
          curl -sL \
            https://api.github.com/repos/egoist/chatwise-releases/releases/latest | \
            jq -r '.assets[] | select(.name | endswith("x86_64.rpm")) | .browser_download_url' | \
            wget -nv -i - -O files/dnf/chatwise.rpm

      - name: Download DBeaver RPM
        run: |
          curl -sL \
            https://api.github.com/repos/dbeaver/dbeaver/releases/latest | \
            jq -r '.assets[] | select(.name | endswith("x86_64.rpm")) | .browser_download_url' | \
            wget -nv -i - -O files/dnf/dbeaver.rpm

      - name: Download OpenCode RPM
        run: |
          curl -sL \
            https://api.github.com/repos/sst/opencode/releases/latest | \
            jq -r '.assets[] | select(.name | endswith("x86_64.rpm")) | .browser_download_url' | \
            wget -nv -i - -O files/dnf/opencode.rpm

      - name: Build Custom Image
        uses: blue-build/github-action@v1
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          skip_checkout: true
          maximize_build_space: false
          use_cache: false

  delete-package-versions:
    name: Delete old packages
    needs: bluebuild
    runs-on: ubuntu-latest
    steps:
      # Delete all packages older than 3 days
      - uses: snok/container-retention-policy@v3.0.1
        with:
          account: user
          token: ${{ secrets.PAT }}
          image-names: "*"
          cut-off: 3d
          dry-run: false
