name: Build and Upload ISOs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 2" # 01:00 UTC every Tuesday

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-upload-isos:
    name: Build and upload ${{ matrix.iso_name }} to B2
    runs-on: ubicloud-standard-4
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - iso_name: kinoite.iso
            image: ghcr.io/purkkis/kinoite:latest
          - iso_name: kinoite-nvidia.iso
            image: ghcr.io/purkkis/kinoite-nvidia:latest
    env:
      B2_ENDPOINT: ${{ secrets.B2_ENDPOINT }}
      B2_BUCKET_NAME: ${{ secrets.B2_BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install bluebuild
        run: |
          bash <(curl -s https://raw.githubusercontent.com/blue-build/cli/main/install.sh)

      - name: Run ISO build script
        run: |
          chmod +x ./build-isos.sh
          ./build-isos.sh "${{ matrix.iso_name }}" "${{ matrix.image }}"
